/*
 * DialogTag.java
 *
 * Created on 20 Апрель 2008 г., 13:27
 */

package mybudget.gui.dialog;

import mybudget.option.Options;
import mybudget.option.PrefValue;

/**
 *
 * @author Alexander Kalinichev / alexander.kalinichev@gmail.com
 */
public class DialogTag extends javax.swing.JDialog {
    
    private String name;
    
    public DialogTag(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        initDialog();
    }
    
    public DialogTag(javax.swing.JDialog parent) {
        super(parent, true);
        initComponents();
        initDialog();
    }
    
    private void initDialog() {
        setSize(Options.PREF.getInt(PrefValue.KEY_DTAG_WIDTH, PrefValue.VAL_DTAG_WIDTH), 
                Options.PREF.getInt(PrefValue.KEY_DTAG_HEIGHT, PrefValue.VAL_DTAG_HEIGHT));
        setLocation(Options.PREF.getInt(PrefValue.KEY_DTAG_X, PrefValue.VAL_DTAG_X), 
                Options.PREF.getInt(PrefValue.KEY_DTAG_Y, PrefValue.VAL_DTAG_Y));
    }
    
    public void showForNew() {
        setTitle(mybudget.option.Options.I18N_BUNDLE.getString("New_Tag"));
        jTextFieldName.setText("");
        jTextFieldName.requestFocus();
        setVisible(true);
    }
    
    public void showForEdit(String name) {
        setTitle(mybudget.option.Options.I18N_BUNDLE.getString("Edit_Tag"));
        jTextFieldName.setText(name);
        jTextFieldName.select(name.length(), name.length());
        jTextFieldName.requestFocus();
        setVisible(true);
    }
    
    public String getResult() {
        return name;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTextFieldName.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel1.add(jTextFieldName, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancel.setText(mybudget.option.Options.I18N_BUNDLE.getString("Cancel")); // NOI18N
        jButtonCancel.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        jButtonOk.setText(mybudget.option.Options.I18N_BUNDLE.getString("OK")); // NOI18N
        jButtonOk.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOk);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        name = null;
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        name = jTextFieldName.getText().trim();
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jButtonCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    
}
