package mybudget.gui.dialog;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import mybudget.option.Options;
import mybudget.option.PrefValue;

/**
 * DialogOptions 09.06.2008 (15:44:26)
 * @author Alexander Kalinichev / alexander.kalinichev@gmail.com
 */
public class DialogOptions extends javax.swing.JDialog {
    
    private boolean result = false;
    private Color colorIncome;
    private Color colorExpense;
    private Color colorBalance;

    /** Creates new form DialogOptions */
    public DialogOptions(java.awt.Frame parent) {
        super(parent);
        initComponents();
        
        initDialogOptions();
    }
    
    private void initDialogOptions() {
        setSize(400, 440);
        setResizable(false);
        setLocation(Options.PREF.getInt(PrefValue.KEY_DO_X, PrefValue.VAL_DO_X), 
                Options.PREF.getInt(PrefValue.KEY_DO_Y, PrefValue.VAL_DO_Y));
    }
    
    public JComboBox getI18NComboBox() {
        return jComboBox1;
    }
    
    public JComboBox getDatePatternComboBox() {
        return jComboBox2;
    }
    
    public boolean getResult() {
        return result;
    }
    
    public Color getColorIncome() {
        return colorIncome;
    }
    
    public Color getColorExpense() {
        return colorExpense;
    }
    
    public Color getColorBalance() {
        return colorBalance;
    }
    
    public void setColorIncome(Color colorIncome) {
        this.colorIncome = colorIncome;
        jPanelColorIncome.setBackground(colorIncome);
    }
    
    public void setColorExpense(Color colorExpense) {
        this.colorExpense = colorExpense;
        jPanelColorExpense.setBackground(colorExpense);
    }
    
    public void setColorBalance(Color colorBalance) {
        this.colorBalance = colorBalance;
        jPanelColorBalance.setBackground(colorBalance);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanelColorIncome = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanelColorExpense = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanelColorBalance = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Options.I18N_BUNDLE.getString("Options")); // NOI18N
        setModal(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(Options.I18N_BUNDLE.getString("Language"))); // NOI18N
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText(Options.I18N_BUNDLE.getString("Select_Language_:_")); // NOI18N
        jPanel5.add(jLabel1, new java.awt.GridBagConstraints());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Русский [Ru]", "English [En]" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(120, 22));
        jPanel5.add(jComboBox1, new java.awt.GridBagConstraints());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabel6.setText(mybudget.option.Options.I18N_BUNDLE.getString("Restart_program_to_change_language.")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        jPanel4.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(Options.I18N_BUNDLE.getString("Colors"))); // NOI18N
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText(Options.I18N_BUNDLE.getString("Income_Color_:_")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText(Options.I18N_BUNDLE.getString("Expense_Color_:_")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText(Options.I18N_BUNDLE.getString("Balance_Color_:_")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jLabel4, gridBagConstraints);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel9.setLayout(new java.awt.BorderLayout());
        jPanel9.add(jPanelColorIncome, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel9, new java.awt.GridBagConstraints());

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel10.add(jPanelColorExpense, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel6.add(jPanel10, gridBagConstraints);

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel11.add(jPanelColorBalance, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel6.add(jPanel11, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton1.setText("...");
        jButton1.setPreferredSize(new java.awt.Dimension(45, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jButton1, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton2.setText("...");
        jButton2.setPreferredSize(new java.awt.Dimension(45, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jButton2, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton3.setText("...");
        jButton3.setPreferredSize(new java.awt.Dimension(45, 20));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(jButton3, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton4.setText(Options.I18N_BUNDLE.getString("Reset_to_default")); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(180, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 3, 3);
        jPanel6.add(jButton4, gridBagConstraints);

        jPanel4.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(Options.I18N_BUNDLE.getString("Date_Format"))); // NOI18N
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText(Options.I18N_BUNDLE.getString("Select_Date_Format_:_")); // NOI18N
        jPanel7.add(jLabel5, new java.awt.GridBagConstraints());

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBox2.setPreferredSize(new java.awt.Dimension(120, 22));
        jPanel7.add(jComboBox2, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel7);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancel.setText(mybudget.option.Options.I18N_BUNDLE.getString("Cancel")); // NOI18N
        jButtonCancel.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCancel);

        jButtonOk.setText(mybudget.option.Options.I18N_BUNDLE.getString("OK")); // NOI18N
        jButtonOk.setPreferredSize(new java.awt.Dimension(90, 23));
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonOk);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        result = false;
        setVisible(false);
}//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        result = true;
        setVisible(false);        
    }//GEN-LAST:event_jButtonOkActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    setColorIncome(JColorChooser.showDialog(this, "", colorIncome));
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    setColorExpense(JColorChooser.showDialog(this, "", colorExpense));
    
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    setColorBalance(JColorChooser.showDialog(this, "", colorBalance));
    
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    setColorIncome(new Color(PrefValue.VAL_INCOME_R, PrefValue.VAL_INCOME_G, PrefValue.VAL_INCOME_B));
    setColorExpense(new Color(PrefValue.VAL_EXPENSE_R, PrefValue.VAL_EXPENSE_G, PrefValue.VAL_EXPENSE_B));
    setColorBalance(new Color(PrefValue.VAL_BALANCE_R, PrefValue.VAL_BALANCE_G, PrefValue.VAL_BALANCE_B));
    
}//GEN-LAST:event_jButton4ActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Generated Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelColorBalance;
    private javax.swing.JPanel jPanelColorExpense;
    private javax.swing.JPanel jPanelColorIncome;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
    
}
