/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TagsPanel.java
 *
 * Created on 19.04.2010, 22:37:28
 */

package mybudget.gui;

import mybudget.gui.updater.ITagsUpdater;
import java.util.List;
import mybudget.database.element.Tag;
import mybudget.database.manager.TagManager;
import mybudget.gui.listeners.TagFilterMouseListener;
import mybudget.table.TagTransactionTable;

/**
 *
 * @author slash
 */
public class TagsPanel extends javax.swing.JPanel {
    /**
     * Менеджер для получения ярлыков
     */
    private TagManager tagManager;
    private TagTransactionTable table;
    private ITagsUpdater updater;

    public TagsPanel(TagManager tag, ITagsUpdater updater) {
        initComponents();
        tagManager = tag;
        this.updater = updater;
    }

    public List<Tag> getSpecificTags() {
        return table == null ? null : table.getSelectedTags();
    }

    public int getSelectedCount() {
        return table == null ? 0 : table.getSelectedCount();
    }

    public void updateContent() {
        List<Tag> prevSpecificTags = getSpecificTags();
        table = new TagTransactionTable(tagManager.getListTagCache());
        if (prevSpecificTags != null) {
            table.selectTags(prevSpecificTags);
            setAllCheckBox(table.getRowCount() <= prevSpecificTags.size());
        }

        table.addMouseListener(new TagFilterMouseListener(this, updater));
        jScrollPane1.setViewportView(table);
    }

    public boolean isAndSelected() {
        return jRadioButtonAnd.isSelected();
    }

    public TagTransactionTable getTable() {
        return table;
    }

    public void setAllCheckBox(boolean isSelected) {
        jCheckBoxAll.setSelected(isSelected);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTag = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxAll = new javax.swing.JCheckBox();
        jRadioButtonOr = new javax.swing.JRadioButton();
        jRadioButtonAnd = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jCheckBoxAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAllActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxAll);

        buttonGroupTag.add(jRadioButtonOr);
        jRadioButtonOr.setSelected(true);
        jRadioButtonOr.setText(mybudget.option.Options.I18N_BUNDLE.getString("Or")); // NOI18N
        jRadioButtonOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTransactionContent(evt);
            }
        });
        jPanel2.add(jRadioButtonOr);

        buttonGroupTag.add(jRadioButtonAnd);
        jRadioButtonAnd.setText(mybudget.option.Options.I18N_BUNDLE.getString("And")); // NOI18N
        jRadioButtonAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTransactionContent(evt);
            }
        });
        jPanel2.add(jRadioButtonAnd);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTransactionContent(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTransactionContent
        if (0 < table.getRowCount()) {
            updater.refresh();
        }
    }//GEN-LAST:event_updateTransactionContent

    private void jCheckBoxAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAllActionPerformed
        table.setCheckAll(jCheckBoxAll.isSelected());
        updateTransactionContent(evt);
    }//GEN-LAST:event_jCheckBoxAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTag;
    private javax.swing.JCheckBox jCheckBoxAll;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAnd;
    private javax.swing.JRadioButton jRadioButtonOr;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
