/*
 * SplashForm.java
 *
 * Created on 16 Май 2008 г., 15:56
 */
package mybudget.gui.splash;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Alexander Kalinichev / alexander.kalinichev@gmail.com
 */
public class SplashForm extends javax.swing.JFrame {

    public SplashForm() {
        initComponents();
        setSize(460, 348);
        Dimension screenDim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((screenDim.width - getWidth()) / 2, (screenDim.height - getHeight()) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Starting myBudget");
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/mybudget/gui/images/logo.png"))).getImage());
        setResizable(false);
        setUndecorated(true);

        jLabelSplash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mybudget/gui/images/bigLogo.png"))); // NOI18N
        getContentPane().add(jLabelSplash, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSplash;
    // End of variables declaration//GEN-END:variables
}
